### ISSUE TITLE
目测失效

### ISSUE THREAD

**Issue by alswl** [justan/gmscrobber#1]
环境：
- ArchLinux / Chormium 19.0.1084.46 / TamperMonkey 2.4.2711 / Script 0.17
- ArchLinux / Firefox 12.0 / GM 0.9.20 / Script 0.17

无法出现菜单，记录功能失效。

**Comment by justan** [comment]
奇怪. 之前我发现不出现菜单是因为  greasemonkey 0.9.19 版本的 [setTimeout 失效](https://github.com/greasemonkey/greasemonkey/issues/1549) 问题.
你用的或许是从 userscript 上安装的 0.17 版本. 
豆瓣电台的初始化流程最近有些变化, 我暂时还没有找到完美的解决办法. 可以先安装 [github 上的版本](https://github.com/justan/gmscrobber/raw/master/dbscrobbler.user.js), 勉强可以使用

**Comment by alswl** [comment]
貌似我明白勉强能用什么意思了，能连接应用，不能记录？

**Comment by justan** [comment]
目前发现有两种情况:
1. 第一首歌不会被记录
2. 电台页面似乎被干扰, 出现诸如白屏之类的现象

但无论如何, 目前的版本是可以记录的

**Comment by alswl** [comment]
不好意思，我误报了
Last.fm 现在已经更新了。

**Comment by alswl** [comment]
哎哟，我发现我之前还提过第一个 issue，我果然是长期用户啊，哈哈哈~

**Comment by justan** [comment]
两年了.
:musical_score:
