### ISSUE TITLE
请求虾米记录时artist.replace(';', '&')

### ISSUE THREAD

**Issue by rekhubs** [justan/gmscrobber#13]
多个艺人时，感觉last.fm更喜欢用“&”，而虾米的是分号。

**Comment by justan** [comment]
你几乎已经把代码写出了. 能否提个 pull request ?
https://github.com/justan/gmscrobber/blob/gh-pages/GMscrobbler_for_xiami.user.js#L41
最新很少用虾米...

**Comment by rekhubs** [comment]
怎么搞啊？直接就把代码改了啊？不会弄。。
