### ISSUE TITLE
请求虾米新在线播放器脚本！

### ISSUE THREAD

**Issue by bearpool** [justan/gmscrobber#15]
不好意思，知道您最近不太在用虾米，但虾米使用新播放器后旧脚本就失效了。

麻烦您更新，谢谢！

**Comment by rekhubs** [comment]
http://userscripts.org/scripts/show/405004
我写了一个简单的。
草稿版，功能简单，什么都不保证。。。

**Comment by bearpool** [comment]
感谢！第一首曲目已经开始记录了……

**Comment by justan** [comment]
https://github.com/justan/gmscrobber/commit/6d4278fd1d70bc2f2f63744022fc8f723e060ba2

请更新
