### ISSUE TITLE
豆瓣电台 / 虾米失效

### ISSUE THREAD

**Issue by justan** [justan/gmscrobber#25]
在 Firefox 30, 及 greasemokey 2.0 后失效.
是 `unsafeWindow` 的变化.

https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/
http://www.greasespot.net/2014/06/greasemonkey-20-release.html

**Comment by justan** [comment]
虾米和豆瓣电台的脚本现阶段不能简单兼容 greasemonkey 和 tampermonkey.
这是个问题.

**Comment by youngton** [comment]
歌曲名称或艺术家名称中带有个别符号的，会被转义，比如 Blur – There's No Other Way 
「'」 在同步到last.fm的时候会转义，变成 Blur – There&#039;s no other way

**Comment by justan** [comment]
@youngton 没明白.
你举的例子前后两个没看出区别..

**Comment by youngton** [comment]
@justan 哦，在这里输入又被反转义了。。
你在虾米上听一下这首，看看同步到last.fm的歌曲名称就知道了 http://www.xiami.com/song/3675875
![qq20140912-1](https://cloud.githubusercontent.com/assets/7427203/4244598/87f13d14-3a24-11e4-96ae-10f3e1d6117c.png)

**Comment by justan** [comment]
貌似没有兼容问题了

https://github.com/justan/gmscrobber/issues/30#issuecomment-159955593
