### ISSUE TITLE
请问网易云音乐网页版如何标记红心

### ISSUE THREAD

**Issue by nkcfan** [justan/gmscrobber#26]
以便Last.fm记下红心标记？
看了下http://justan.github.io/gmscrobber/的说明，好像是支持的。

**Comment by justan** [comment]
1. 点下面播放控制条上的收藏按钮
2. 点我喜爱的音乐

**Comment by nkcfan** [comment]
我更新了刚才最新的版本，然后试出来你给的方法，成功了！
非常感谢！网易上打个红心还要点两下，真是不直观，当然这不是脚本的问题了
