### ISSUE TITLE
请把库文件放到 greasyfork.org 上

### ISSUE THREAD

**Issue by legendtang** [justan/gmscrobber#28]
``` JavaSrcipt
// @require     https://raw.github.com/justan/lrc/master/lrc.js
// @require     http://justan.github.io/gmscrobber/simple_scrobbler_user.js
```

请把这些 require 文件添加到 greasyfork 上以方便更多的人编写和更新 scrobber，由于 greasyfork 的政策目前只支持上传的库文件调用和公共 CDN 库文件调用

如果可以的话也请将原本在 userscript 上放置的脚本转移到 greasyfork 上来方便更多的人更新谢谢！

我写了一个萌否电台的 scrobber ，已请求 pull request

**Comment by justan** [comment]
这两个依赖我提交的版本在这:
https://greasyfork.org/zh-CN/scripts/7806-gmscrobber
https://greasyfork.org/zh-CN/scripts/7807-lrc-paser

https://greasyfork.org/ 网站貌似比以前的 userscript.org 好用多了.
