### ISSUE TITLE
落网失效

### ISSUE THREAD

**Issue by luboq** [justan/gmscrobber#34]
落网的失效了。测试链接：http://www.luoo.net/music/899

**Comment by justan** [comment]
重新安装下

**Comment by luboq** [comment]
@justan 哎呀，重复劳动了。根据你写的QQ音乐的脚本，我改了个能用的落网。谢谢

**Comment by justan** [comment]
👍  
落网脚本现在的版本在自动换歌的时候用问题, 欢迎 pr
