### ISSUE TITLE
脚本正常运行 但是无法同步到lastfm

### ISSUE THREAD

**Issue by stefanielyq** [justan/gmscrobber#36]
![image](https://cloud.githubusercontent.com/assets/16235150/25930486/0e213a8e-3639-11e7-8937-dcc49903cfd3.png)
![image](https://cloud.githubusercontent.com/assets/16235150/25930492/1cb7638e-3639-11e7-9fff-8e2ce3a941d4.png)
网页收听的都无法同步。。。。是需要重新认证吗？怎么设置？

**Comment by stefanielyq** [comment]
自己研究了一下 解决问题了
把脚本里所有的http都换成了https~又可以记录了~

**Comment by justan** [comment]
:+1:  欢迎 PR
