### ISSUE TITLE
是不是失效了，例如豆瓣fm

### ISSUE THREAD

**Issue by antizo** [justan/gmscrobber#39]

**Comment by antizo** [comment]
插件安装了，也启用了，但是在豆瓣fm里面无法探测的到

**Comment by justan** [comment]
有些的脚本年久失修。
豆瓣 fm 亲测还能用

**Comment by antizo** [comment]
> 有些的脚本年久失修。
> 豆瓣 fm 亲测还能用

因为自己只用豆瓣fm，就是时灵时不灵的。

**Comment by justan** [comment]
遇到不能用的时候可以 F12 打开控制台截图错误信息, 这样应该容易找出问题来
