### ISSUE TITLE
豆瓣电台未响应

### ISSUE THREAD

**Issue by mzcabc** [justan/gmscrobber#4]
Chrome26.0.1410.5 下每当歌曲结束下一首时，豆瓣电台就未响应了
望解决

**Comment by justan** [comment]
Canary 版 chrome 对 `regexp.exec` 和 `regexp.lastIndex` 的实现有问题, 导致歌词解析程序出现[死循环](https://github.com/justan/lrc/blob/2f33359a68643b8c13a5010bfd1fd0dc7c572382/lrc.js#L45).
暂时的解决办法是去掉 meta 头的: `// @require        https://raw.github.com/justan/lrc/master/lrc.js`, 代价是不能显示同步歌词

**Comment by mzcinf** [comment]
谢谢 已经可以正常记录到last.fm了
