### ISSUE TITLE
无法跳转last.fm认证

### ISSUE THREAD

**Issue by AliceSunJiawen** [justan/gmscrobber#40]
<img width="1499" alt="截屏2023-04-06 21 52 33" src="https://user-images.githubusercontent.com/125879633/230398862-f1f52545-01bb-4552-9240-49c9836888fd.png">

使用Tampermonkey开启脚本运转后，无法自动跳转last.fm认证，是什么问题呢

**Comment by justan** [comment]
https://github.com/justan/gmscrobber/blob/gh-pages/scrobblers/qqmusicscrobber.user.js
现在匹配的是播放器的页面，所以应该需要进入播放器后，才会激活脚本并看到脚本菜单
