### ISSUE TITLE
网易云音乐有bug

### ISSUE THREAD

**Issue by goxofy** [justan/gmscrobber#7]
无论听多少首，lastfm那边记录的永远都是当前歌曲，之前同步的会被清除

**Comment by justan** [comment]
不太清楚是什么问题.

想说我刚试了没问题.

**Comment by justan** [comment]
@goxofy 能说明下详细的浏览器/操作系统版本么

**Comment by goxofy** [comment]
额，chrome 30.0.1599.69 m

win7

**Comment by bearpool** [comment]
借楼

我这边不知道为什么突然不能记录
Tampermonkey也试着重装过了
顺便，另一边的xiami脚本一切正常

控制台里的错误信息：
Tampermonkey started VM804:106
GET http://music.163.com/UA-38766552-1/__utm.gif?utmwv=5.4.5dc&utms=8&utmn=5237…F%91%E7%8E%B0%E5%A5%BD%E9%9F%B3%E4%B9%90&utmhid=1066791311&utmr=-&utmp=%2F net::ERR_BLOCKED_BY_CLIENT ga.js:61
GET http://music.163.com/UA-38766552-1/__utm.gif?utmwv=5.4.5dc&utms=9&utmn=1758…8E%B0%E5%A5%BD%E9%9F%B3%E4%B9%90&utmhid=1113146576&utmr=0&utmp=%2Fdiscover net::ERR_BLOCKED_BY_CLIENT ga.js:61
ERROR: Execution of script '网易云音乐 scrobbler' failed! Scrobbler is not defined VM1121:235
ReferenceError: Scrobbler is not defined
    at Object.eval (unknown source)), 168:21)
    at Object.eval (unknown source)), 236:4)
    at ag (unknown source), 190:4)
    at K (unknown source), 190:46)
    at o (unknown source), 456:2)
    at U (unknown source), 460:85)
    at R (unknown source), 229:40) VM1121:235

**Comment by justan** [comment]
@bearpool 已修复. 请更新脚本
#17 
https://github.com/justan/gmscrobber/commit/7f60ec6db7be2c4190a8a6f6d73df3f018cadfb6

**Comment by mustang129** [comment]
感觉不是马上记录音乐，是等歌曲放完才记录吗？还是设置了延迟？
